swagger: "2.0"
info:
  description: "REST PlagChecker"
  version: "1.0.0"
  title: "REST PlagChecker"
host: "127.0.0.1:5050"
basePath: "/"
schemes:
- "http"


tags:
- name: lab
- name: algorithms


paths:

  /lab:
    put:
      tags: 
      - lab
      description: "Сохранить лабу на сервере"
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: archive
        description: "zip архив с файлами лабы"
        in: formData
        type: file
        required: true
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "id лабы в системе"
    
    delete:
      tags:
      - lab
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: lab_id
        description: "id лабы в системе"
        in: query
        type: integer
        required: true
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              status:
                default: "OK"
              
                
  /score/all:
    post:
      tags:
      - algorithms
      description: "Сравнение всеми реализованными алгоритмами"
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: archive
        description: "zip архив с файлами лабы"
        in: formData
        type: file
        required: true
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              similars:
                type: array
                items:
                  type: object
                  properties:
                    algorithm:
                      type: string
                      description: "Название алгоритма"
                    top:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: "id лабы"
                          score:
                            type: number
                            description: "мера схожести"
                            
                  

  /score/levenstein:
    post:
      tags:
      - algorithms
      description: "Сравнение алгоритмом Левенштейна"
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: archive
        description: "zip архив с файлами лабы"
        in: formData
        type: file
        required: true
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              similars:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: "id лабы"
                    score:
                      type: number
                      description: "мера схожести"
                  

